env:
  global:
    - CC_TEST_REPORTER_ID=9d39e517e2a74afe27c5d9b783a86db53babf6c3bd498fab51605c661be3c271
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- "pip install pyaml==16.12.2"
- "pip install gitpython==2.1.8"
- "pip install svn==0.3.44"
- "pip install docopt==0.6.2"
- "pip install pytest-cov"
- "pip install docker-compose>=1.11.2"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
- "python setup.py test"
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: pypi
  user: swf.operations
  password:
    secure: cwS9IQ1F2NrHWtFG2otSS06zwUYUpASu6gwHexomAnS2p8boOBlT1/VGfihY9YnE8fd6G/9lo91Nqz0a0e4PGAXLzgXvEnPitVKTi5OzYrYAB6zHw1QCLeEAfD/FKOFhUW4jx05zYA5G2xTvrk+72vReASnfVFk7sz0iYhCdkkY4nB+qBacIKZIInhI7fgReU91DT05Tn92gPAXnUPQSh2HO0FTpAGgp0FCiH+ADSEFUhJkeKqz9W8QoCCqjsQFB0ye8li4JC50pE2KcL0uUyL7llJQ7ar4+ox8Yo4nzxQ8SnKVVDyGdKMyuDWCqUIJ2G31kprezQvzHTC5QRgxWGvjMRz7sBUnKEzirc5YV4kiCtGLbkQdhDifBkj/Psz5OVmDjvS6IfodkyLST5Xr7tBd341nXstUoBP08ZD5VzyxfMS+wYjf+p00NsAxa7Xwamd1lfEWd9g1VyuRL6z1XgXorYUn4uoMYRXgggP8XlusLaeShylvYV2LUL3FQmSKabn5LttT+ne+bSs+l39Wr3j/1mrKni0Ms/EPQTbgA88UMHj+HvVu8X8dPAc5vFfuPjnUhPD5hg9tWjuzYzrdl8WvtvVUdFX2UbQCFno5ueHad5ponmFcODiVLLUGfjHrqj4UPh5coO2mmKAHmwA0qGHgRMGs/dDmtdiTll9QWbuI=
  on:
    tags: true
    branch: master